# Generated by Django 5.2.7 on 2025-11-10 05:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAjuste',
            fields=[
                ('id_tipo_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('cumplimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('estado_caso', models.CharField(max_length=50)),
                ('fecha_matricula', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('estado_caso', models.CharField(max_length=50)),
                ('evaluacion', models.TextField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignatura', to='api.asignatura')),
                ('id_usuario_asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asesor', to='api.asesor')),
                ('id_usuario_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_estudiante', to='api.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ajuste', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('id_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='api.caso')),
                ('id_usuario_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to='api.director')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('url_archivo', models.URLField()),
                ('fecha_subida', models.DateField(default=datetime.datetime.now)),
                ('id_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField(default='Texto de notificación')),
                ('fecha_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_usuario_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_impartidas', to='api.docente'),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrevista', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('id_usuario_asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_realizadas', to='api.asesor')),
                ('id_usuario_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_recibidas', to='api.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('id_usuario_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'unique_together': {('id_asignatura', 'id_usuario_estudiante')},
            },
        ),
    ]
