# Generated by Django 5.2.7 on 2025-12-18 16:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=190, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descipción del ajuste')),
                ('tipo', models.CharField(choices=[('Presentacion', 'Presentacion de la informacion'), ('Entorno', 'Entorno'), ('Forma', 'Forma de respuesta'), ('Tiempo', 'Organizacion del tiempo y horario')], default='Presentacion', max_length=20)),
            ],
            options={
                'verbose_name': 'Ajuste Razonable',
                'verbose_name_plural': 'Ajustes Razonables',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('estado_caso', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Abierto', 'Abierto'), ('Finalizado', 'Finalizado')], default='Iniciado', max_length=12)),
                ('fecha_ingreso_caso', models.DateField(default=datetime.datetime.now)),
                ('semestre', models.CharField(blank=True, max_length=8)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Caso')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.CharField(choices=[('Pedagogico', 'Asesor Pedagogico'), ('CTP', 'Asesor CTP')], default='CTP', max_length=25)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('area_asignada', models.CharField(blank=True, help_text='Area de carrera asignada para Asesores CTP', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('cumplimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=14)),
                ('carrera', models.CharField(blank=True, max_length=100)),
                ('cede', models.CharField(blank=True, max_length=100)),
                ('fecha_matricula', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios', models.TextField(blank=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de la entrevista')),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('No Asistio', 'Estudiante no asistió')], default='Programada', max_length=20)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='api.caso')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.motivocaso', verbose_name='Motivo del Caso'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField(default='Texto de notificación')),
                ('fecha_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Propuesto', 'Propuesto por asesor'), ('Aprobado', 'Aprobado por Director/CTP'), ('Rechazado', 'Rechazado')], default='Propuesto', max_length=20)),
                ('comentario_desicion', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ajuste')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_solicitados', to='api.caso')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='ajustes',
            field=models.ManyToManyField(blank=True, related_name='casos', through='api.SolicitudAjuste', to='api.ajuste'),
        ),
        migrations.AddField(
            model_name='caso',
            name='id_usuario_asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asesor', to='api.asesor'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=200)),
                ('id_usuario_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_impartidas', to='api.docente')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='id_usuario_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_estudiante', to='api.estudiante'),
        ),
    ]
