# Generated by Django 5.2.7 on 2025-11-23 01:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_usuario_estudiante',
        ),
        migrations.RenameField(
            model_name='ajuste',
            old_name='estado',
            new_name='estado_ajuste',
        ),
        migrations.RenameField(
            model_name='caso',
            old_name='id_diagnostico',
            new_name='id_caso',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='asignatura_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.asignatura'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='id_usuario_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_estudiante', to='api.estudiante'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='titulo_ajuste',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='fecha_ingreso_caso',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='caso',
            name='semestre',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cede',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ajuste',
            name='id_usuario_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to='api.director'),
        ),
        migrations.AlterField(
            model_name='ajuste',
            name='tipo_ajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoajuste'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='id_usuario_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_estudiante', to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='id_usuario_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_recibidas', to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MotivoCaso',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('id_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_caso', to='api.caso')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
