# Generated by Django 5.2.7 on 2025-12-09 15:51
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils import timezone

def crear_estudiantes(apps, schema_editor):
    Usuario = apps.get_model('api', 'Usuario')
    Estudiante = apps.get_model('api', 'Estudiante')

    contrasena = make_password('Inacap2025') #Crea una contraseña hasheada

    # ==============================================================================
    # 2. CREAR ESTUDIANTE
    # ==============================================================================
    u_est, created = Usuario.objects.update_or_create(
        correo='estudiante2@inacap.cl',
        defaults={
            'nombre': 'Ana González',
            'contrasena': contrasena, # Guardamos el HASH, no el texto plano
            'rol': 'Estudiante'
        }
    )
    # Crear perfil si no existe
    if not Estudiante.objects.filter(pk=u_est).exists():
        Estudiante.objects.create(
            id_usuario=u_est,
            rut='21.234.567-8',
            carrera='Analista Programador',
            cede='Temuco',
            telefono='+56911122233',
            fecha_matricula=timezone.now()
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuarios_prueba'),
    ]

    operations = [
        migrations.RunPython(crear_estudiantes),
    ]
