# Generated by Django 5.2.7 on 2025-11-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_inscripcion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='area_asignada',
            field=models.CharField(blank=True, help_text='Area de carrera asignada para Asesores CTP', max_length=100),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='especialidad',
            field=models.CharField(choices=[('Pedagogico', 'Asesor Pedagogico'), ('CTP', 'Asesor CTP')], default='CTP', max_length=25),
        ),
    ]
