# Generated by Django 5.2.7 on 2025-12-01 03:35

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils import timezone

def crear_usuarios_de_prueba(apps, schema_editor):
    Usuario = apps.get_model('api', 'Usuario')
    Estudiante = apps.get_model('api', 'Estudiante')
    Asesor = apps.get_model('api', 'Asesor')
    Docente = apps.get_model('api', 'Docente')
    Director = apps.get_model('api', 'Director')

    contrasena = make_password('Inacap2025') #Crea una contraseña hasheada

    # ==============================================================================
    # 2. CREAR ESTUDIANTE
    # ==============================================================================
    u_est, created = Usuario.objects.update_or_create(
        correo='estudiante@inacap.cl',
        defaults={
            'nombre': 'Matias Urra',
            'contrasena': contrasena, # Guardamos el HASH, no el texto plano
            'rol': 'Estudiante'
        }
    )
    # Crear perfil si no existe
    if not Estudiante.objects.filter(pk=u_est).exists():
        Estudiante.objects.create(
            id_usuario=u_est,
            rut='22.111.111-1',
            carrera='Ingeniería Informática',
            cede='Temuco',
            estado_caso='Sin Caso',
            fecha_matricula=timezone.now()
        )

    # ==============================================================================
    # 3. CREAR ASESOR PEDAGÓGICO
    # ==============================================================================
    u_asesor1, created = Usuario.objects.update_or_create(
        correo='asesor.pedagogico@inacap.cl',
        defaults={
            'nombre': 'Valentina Mora',
            'contrasena': contrasena,
            'rol': 'Asesor'
        }
    )
    if not Asesor.objects.filter(pk=u_asesor1).exists():
        Asesor.objects.create(
            id_usuario=u_asesor1,
            especialidad='Pedagogico',
            telefono_contacto='+56912345678'
        )

    # ==============================================================================
    # 4. CREAR ASESOR CTP (Inclusión/Técnico)
    # ==============================================================================
    u_asesor2, created = Usuario.objects.update_or_create(
        correo='asesor.ctp@inacap.cl',
        defaults={
            'nombre': 'Carlos Ruiz',
            'contrasena': contrasena,
            'rol': 'Asesor'
        }
    )
    if not Asesor.objects.filter(pk=u_asesor2).exists():
        Asesor.objects.create(
            id_usuario=u_asesor2,
            especialidad='CTP', 
            telefono_contacto='+56933334444'
        )

    # ==============================================================================
    # 5. CREAR DOCENTE
    # ==============================================================================
    u_docente, created = Usuario.objects.update_or_create(
        correo='docente@inacap.cl',
        defaults={
            'nombre': 'Marcelo Alvarado',
            'contrasena': contrasena,
            'rol': 'Docente'
        }
    )
    if not Docente.objects.filter(pk=u_docente).exists():
        Docente.objects.create(
            id_usuario=u_docente,
            observaciones='a',
            cumplimiento=True
        )

    # ==============================================================================
    # 6. CREAR DIRECTOR
    # ==============================================================================
    u_director, created = Usuario.objects.update_or_create(
        correo='director@inacap.cl',
        defaults={
            'nombre': 'Monica Vera',
            'contrasena': contrasena,
            'rol': 'Director'
        }
    )
    # Director tiene lógica diferente (id_director propio)
    if not Director.objects.filter(id_usuario=u_director).exists():
        Director.objects.create(
            id_usuario=u_director,
            comentarios='b'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_asesor_area_asignada_alter_asesor_especialidad'),
    ]

    operations = [
        migrations.RunPython(crear_usuarios_de_prueba),
    ]
