# Generated by Django 5.2.7 on 2025-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_de_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
