# Generated by Django 5.2.7 on 2025-12-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_estudiante_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estado_caso',
        ),
    ]
